-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 10:51:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`beguda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`beguda` (
  `begudaID` INT NOT NULL AUTO_INCREMENT,
  `nomBeguda` VARCHAR(30) NOT NULL,
  `descripcioBeguda` TEXT NULL DEFAULT NULL,
  `imatgeBeguda` BLOB NULL DEFAULT NULL,
  `preuBeguda` INT NOT NULL,
  PRIMARY KEY (`begudaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `provinciaId` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`provinciaId`),
  UNIQUE INDEX `provincia_UNIQUE` (`provincia` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localitat` (
  `idLocalitat` INT NOT NULL AUTO_INCREMENT,
  `localitat` VARCHAR(30) NOT NULL,
  `Provincia` INT NOT NULL,
  PRIMARY KEY (`idLocalitat`),
  UNIQUE INDEX `localitat_UNIQUE` (`localitat` ASC) ,
  INDEX `Provincia_idx` (`Provincia` ASC) VISIBLE,
  CONSTRAINT `Provincia`
    FOREIGN KEY (`Provincia`)
    REFERENCES `pizzeria`.`provincia` (`provinciaId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `idbotiga` INT NOT NULL AUTO_INCREMENT,
  `adreçaBotiga` VARCHAR(45) NOT NULL,
  `CP` INT NOT NULL,
  `localitat` INT NOT NULL,
  `provincia` INT NOT NULL,
  PRIMARY KEY (`idbotiga`),
  INDEX `localitatTenda_idx` (`localitat` ASC) ,
  INDEX `provinicia_idx` (`provincia` ASC) ,
  CONSTRAINT `localitatTenda`
    FOREIGN KEY (`localitat`)
    REFERENCES `pizzeria`.`localitat` (`idLocalitat`),
  CONSTRAINT `provinicia`
    FOREIGN KEY (`provincia`)
    REFERENCES `pizzeria`.`localitat` (`idLocalitat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(90) NOT NULL,
  `CP` INT NOT NULL,
  `telefon` INT UNSIGNED NOT NULL,
  `provinciaId` INT NOT NULL,
  `localitatId` INT NOT NULL,
  PRIMARY KEY (`idclients`),
  INDEX `localitat_idx` (`localitatId` ASC) ,
  INDEX `privinciaClient_idx` (`provinciaId` ASC) ,
  CONSTRAINT `localitatClient`
    FOREIGN KEY (`localitatId`)
    REFERENCES `pizzeria`.`localitat` (`idLocalitat`),
  CONSTRAINT `provinciaClient`
    FOREIGN KEY (`provinciaId`)
    REFERENCES `pizzeria`.`provincia` (`provinciaId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`hamburguesa` (
  `hamburguesaID` INT NOT NULL AUTO_INCREMENT,
  `nomHamburguesa` VARCHAR(30) NOT NULL,
  `descripcio` TEXT NULL DEFAULT NULL,
  `imatgeHamburguesa` BLOB NULL DEFAULT NULL,
  `preuHambuerguesa` INT NOT NULL,
  PRIMARY KEY (`hamburguesaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizza` (
  `pizzaID` INT NOT NULL AUTO_INCREMENT,
  `nomPizza` VARCHAR(30) NOT NULL,
  `descripcioPizza` TEXT NULL DEFAULT NULL,
  `imatgePizza` BLOB NULL DEFAULT NULL,
  `preuPizza` INT NOT NULL,
  PRIMARY KEY (`pizzaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `idComanda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `aDomicil` TINYINT NOT NULL,
  `numeroPizza` INT NOT NULL DEFAULT '0',
  `numeroBeguda` INT NOT NULL DEFAULT '0',
  `numeroHamburguesa` INT NOT NULL DEFAULT '0',
  `preu` INT NOT NULL,
  PRIMARY KEY (`idComanda`),
  INDEX `pizzes_idx` (`numeroPizza` ASC) ,
  INDEX `hamburgueses_idx` (`numeroHamburguesa` ASC) ,
  INDEX `begudes_idx` (`numeroBeguda` ASC) ,
  CONSTRAINT `begudes`
    FOREIGN KEY (`numeroBeguda`)
    REFERENCES `pizzeria`.`beguda` (`begudaID`),
  CONSTRAINT `hamburgueses`
    FOREIGN KEY (`numeroHamburguesa`)
    REFERENCES `pizzeria`.`hamburguesa` (`hamburguesaID`),
  CONSTRAINT `pizzes`
    FOREIGN KEY (`numeroPizza`)
    REFERENCES `pizzeria`.`pizza` (`pizzaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`treballador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`treballador` (
  `idtreballdor` INT NOT NULL AUTO_INCREMENT,
  `nomTreballador` VARCHAR(45) NOT NULL,
  `cognomTreballador` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  `telefon` INT NOT NULL,
  `repartidor` TINYINT NOT NULL,
  `tenda` INT NOT NULL,
  PRIMARY KEY (`idtreballdor`),
  INDEX `tendaId_idx` (`tenda` ASC) ,
  CONSTRAINT `tendaId`
    FOREIGN KEY (`tenda`)
    REFERENCES `pizzeria`.`botiga` (`idbotiga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
