-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 11:53:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optica_cul_d'ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica_cul_d'ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica_cul_d'ampolla` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `optica_cul_d'ampolla` ;

-- -----------------------------------------------------
-- Table `optica_cul_d'ampolla`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_cul_d'ampolla`.`proveidor` (
  `idProveidor` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(45) NOT NULL,
  `nomProveïdor` VARCHAR(45) NOT NULL,
  `carrerProveidor` VARCHAR(90) NOT NULL,
  `numeroCarrerProveidor` INT NOT NULL,
  `pisPorta` VARCHAR(8) NOT NULL,
  `CP` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `proveidorcol` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `fax` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProveidor`),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC) ,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) ,
  UNIQUE INDEX `fax_UNIQUE` (`fax` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica_cul_d'ampolla`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_cul_d'ampolla`.`marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nomMarca` VARCHAR(45) NOT NULL,
  `proveïdorId` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `proveidor_id_idx` (`proveïdorId` ASC) ,
  CONSTRAINT `proveidor_id`
    FOREIGN KEY (`proveïdorId`)
    REFERENCES `optica_cul_d'ampolla`.`proveidor` (`idProveidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica_cul_d'ampolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_cul_d'ampolla`.`ulleres` (
  `idUlleres` INT NOT NULL AUTO_INCREMENT,
  `IdMarca` INT NOT NULL,
  `graduacio` INT NOT NULL,
  `tipus` VARCHAR(10) NOT NULL COMMENT 'flotant-pasta-met·lalica',
  `colorMunt` VARCHAR(30) NOT NULL,
  `colorVidre` VARCHAR(12) NOT NULL,
  `preu` INT NOT NULL,
  PRIMARY KEY (`idUlleres`),
  INDEX `marca_idx` (`IdMarca` ASC) ,
  CONSTRAINT `Marca_id`
    FOREIGN KEY (`IdMarca`)
    REFERENCES `optica_cul_d'ampolla`.`marca` (`idMarca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica_cul_d'ampolla`.`venedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_cul_d'ampolla`.`venedor` (
  `idVenedor` INT NOT NULL AUTO_INCREMENT,
  `nomVenedor` VARCHAR(45) NOT NULL,
  `ulleresVengudesId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idVenedor`),
  INDEX `ulleresVengudes_idx` (`ulleresVengudesId` ASC) ,
  CONSTRAINT `ulleresVengudes`
    FOREIGN KEY (`ulleresVengudesId`)
    REFERENCES `optica_cul_d'ampolla`.`ulleres` (`idUlleres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica_cul_d'ampolla`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_cul_d'ampolla`.`clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(90) NOT NULL,
  `telefon` INT NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `data` DATETIME NOT NULL,
  `venedor` INT NOT NULL,
  `recomanador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `venedorId_idx` (`venedor` ASC) ,
  INDEX `venedor_idx` (`venedor` ASC) ,
  INDEX `recomandorId_idx` (`recomanador` ASC) ,
  CONSTRAINT `recomandorId`
    FOREIGN KEY (`recomanador`)
    REFERENCES `optica_cul_d'ampolla`.`clients` (`idClient`),
  CONSTRAINT `venedor`
    FOREIGN KEY (`venedor`)
    REFERENCES `optica_cul_d'ampolla`.`venedor` (`idVenedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
